import Navbar from "@/components/general/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="winter">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
